name: gen3-ncov
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - augur
  - auspice
  - nextstrain-cli
  - nextalign
  - snakemake
  - awscli
  - git
  - nextclade
  - nextalign
  - pangolin
  - pangolearn
  - pip
  - pip:
    - biopython
    - pandas
    - requests
    - -e ./gen3-augur
